### ISSUE TITLE
missing readme images

### ISSUE THREAD

**Issue by OzBob** [NetCoreWebApps/Rockwind.Azure#1]
https://github.com/NetCoreWebApps/rockwind-azure/blob/master/README.md

has links to:
https://github.co

1. m/NetCoreWebApps/rockwind-azure/blob/master/docs/images/3-createdocker.png
2. https://github.com/sharp-apps/rockwind-azure/blob/master/docs/images/1-createregistry.png
3. https://github.com/NetCoreWebApps/rockwind-azure/blob/master/docs/images/6-appsettings.png

All of which are missing and not present in the whole of GitHub:
https://github.com/search?q=2-registrysettings.png&type=Code
nor in the docs repo:
https://github.com/ServiceStack/docs/search?q=2-registrysettings.png&unscoped_q=2-registrysettings.png

**Comment by mythz** [comment]
That's the old project, all Sharp App's have moved to:

### https://github.com/sharp-apps

e.g. https://github.com/sharp-apps/rockwind-azure

I've updated https://github.com/NetCoreWebApps/rockwind-azure with a link to the project's new location.
